# Generated by Django 2.0 on 2019-04-06 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicehub', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_info',
            name='service_provider_assign',
            field=models.CharField(default='no', max_length=200),
        ),
        migrations.AlterField(
            model_name='service_provider',
            name='profile_img',
            field=models.FileField(blank=True, default='set.jpg', null=True, upload_to=''),
        ),
    ]
