# Generated by Django 2.0 on 2019-04-06 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicehub', '0002_auto_20190406_1646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order_info',
            name='service_provider_assign',
            field=models.CharField(max_length=200),
        ),
    ]
