# Generated by Django 2.0 on 2019-04-10 05:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servicehub', '0003_auto_20190406_1653'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='rating',
        ),
    ]
