# Generated by Django 2.0 on 2019-04-12 06:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('servicehub', '0004_remove_feedback_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order_info',
            name='service_provider_assign',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servicehub.Service_provider'),
        ),
    ]
