# Generated by Django 2.0 on 2019-04-12 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicehub', '0005_auto_20190412_1130'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_info',
            name='status',
            field=models.CharField(default='Pending', max_length=200),
        ),
    ]
